/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForgotPassword;

import static LibrarianPackage.SecretQuestion.hashSecretAnswer;
import Logins.LoginForm;
import config.Config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SCC
 */
public class Confirmation extends javax.swing.JFrame {

    private String confirmedUserId;
    
    public Confirmation(String verifiedUserId) {
 
     this.confirmedUserId = verifiedUserId;
        initComponents();
    }
    
       public void setconfirmedUserId(String verifiedUserId) {
        this.confirmedUserId = verifiedUserId;
    }

    // Getter method to retrieve the verified user ID
    public String getconfirmedUserId() {
        return this.confirmedUserId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uID = new javax.swing.JTextField();
        CondfButton = new javax.swing.JButton();
        CandfButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sQuestion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sAnswer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detail Verification");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 200, 50));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("User ID*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 50, 20));

        uID.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        uID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(uID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 300, 40));

        CondfButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        CondfButton.setText("Confirm");
        CondfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CondfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CondfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, 40));

        CandfButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        CandfButton.setText("Cancel");
        CandfButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                CandfButtonComponentMoved(evt);
            }
        });
        CandfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CandfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 100, 40));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Security Question*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 130, 20));

        sQuestion.setBackground(new java.awt.Color(204, 255, 255));
        sQuestion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        sQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Security Question", "What is your Mother's middle name?", "What was the name of your first pet?", "What is your favorite sport?" }));
        jPanel1.add(sQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 300, 40));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Answer*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 60, 20));

        sAnswer.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        sAnswer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        sAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAnswerActionPerformed(evt);
            }
        });
        jPanel1.add(sAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CondfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CondfButtonActionPerformed
    String userId = uID.getText().trim();
    String selectedQuestion = sQuestion.getSelectedItem().toString();
    String inputAnswer = sAnswer.getText().trim(); // Only input needed now

    if (userId.isEmpty() || inputAnswer.isEmpty()) {
    JOptionPane.showMessageDialog(
        null,
        "ID and secret answer are required.",
        "Validation Error",
        JOptionPane.WARNING_MESSAGE
    );
    return;
}

    String sql = "SELECT secret_question, secret_answer FROM user WHERE u_id = ?";

    try (Connection conn = Config.getConnection();
         PreparedStatement pst = conn.prepareStatement(sql)) {

        pst.setString(1, userId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String dbQuestion = rs.getString("secret_question");
            String dbHashedAnswer = rs.getString("secret_answer");

            String hashedInputAnswer = hashSecretAnswer(inputAnswer); // Hash user input

            boolean questionMatch = selectedQuestion.equalsIgnoreCase(dbQuestion);
            boolean answerMatch = hashedInputAnswer.equals(dbHashedAnswer);

            if (questionMatch && answerMatch) {
                JOptionPane.showMessageDialog(
                    null,
                    "Verification successful! You may now reset your password.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
                );

                // Open password reset window
                NewPassword np = new NewPassword(userId);
                np.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(
                    null,
                    "Secret question and answer do not match.",
                    "Verification Failed",
                    JOptionPane.ERROR_MESSAGE
                );
            }

        } else {
            JOptionPane.showMessageDialog(
                null,
                "User ID not found.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(
            null,
            "Database error: " + ex.getMessage(),
            "SQL Error",
            JOptionPane.ERROR_MESSAGE
        );
        ex.printStackTrace();
    }

    LoginForm lf = new LoginForm();
        this.dispose();
        lf.setVisible(true);
    }//GEN-LAST:event_CondfButtonActionPerformed

    private void CandfButtonComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CandfButtonComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_CandfButtonComponentMoved

    private void CandfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandfButtonActionPerformed
        LoginForm lf = new LoginForm();
        this.dispose();
        lf.setVisible(true);
    }//GEN-LAST:event_CandfButtonActionPerformed

    private void sAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sAnswerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        String confirmedUserId = "someUserId";
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirmation(confirmedUserId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CandfButton;
    private javax.swing.JButton CondfButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sAnswer;
    private javax.swing.JComboBox<String> sQuestion;
    private javax.swing.JTextField uID;
    // End of variables declaration//GEN-END:variables
}
