/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForgotPassword;

import config.Config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SCC
 */
public class Confirmation extends javax.swing.JFrame {

    private String confirmedUserId;
    
    public Confirmation(String verifiedUserId) {
 
     this.confirmedUserId = verifiedUserId;
        initComponents();
    }
    
       public void setconfirmedUserId(String verifiedUserId) {
        this.confirmedUserId = verifiedUserId;
    }

    // Getter method to retrieve the verified user ID
    public String getconfirmedUserId() {
        return this.confirmedUserId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        uEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uFName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uLName = new javax.swing.JTextField();
        CondfButton = new javax.swing.JButton();
        CandfButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detail Verification");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 200, 50));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("User ID*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 50, 20));

        uID.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        uID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(uID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 230, 40));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Email*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 50, 20));

        uEmail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        uEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(uEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, 40));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("First Name*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 70, 20));

        uFName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        uFName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        uFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uFNameActionPerformed(evt);
            }
        });
        jPanel1.add(uFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 230, 40));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Last Name*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 70, 20));

        uLName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        uLName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(uLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 230, 40));

        CondfButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        CondfButton.setText("Confirm");
        CondfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CondfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CondfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, 40));

        CandfButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        CandfButton.setText("Cancel");
        jPanel1.add(CandfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uFNameActionPerformed

    private void CondfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CondfButtonActionPerformed
        String userId = uID.getText().trim();
        String inputFname = uEmail.getText().trim();
        String inputLname = uFName.getText().trim();
        String inputEmail = uLName.getText().trim();

if (!userId.equals(confirmedUserId)) {  
    JOptionPane.showMessageDialog(null, "ID does not match! Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

try (Connection conn = Config.getConnection();
     PreparedStatement pst = conn.prepareStatement(
         "SELECT u_email, u_firstname, u_lastname FROM user WHERE u_id = ?")) {

    pst.setString(1, userId);
    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
       
        String dbFname = rs.getString("u_email");
        String dbLname = rs.getString("u_firstname");
        String dbEmail = rs.getString("u_lastname");

        // Check if user input matches database records
        if (inputFname.equalsIgnoreCase(dbFname) &&
            inputLname.equalsIgnoreCase(dbLname) &&
            inputEmail.equalsIgnoreCase(dbEmail)) {

            JOptionPane.showMessageDialog(null, "Verified Successfully!", 
                                          "Success", JOptionPane.INFORMATION_MESSAGE);

            // Open the NewPassword frame
            NewPassword np = new NewPassword(confirmedUserId);
            np.setVisible(true);
            this.dispose(); // Close current frame

        } else {
            JOptionPane.showMessageDialog(null, "Credentials are incorrect!", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }

    } else {
        JOptionPane.showMessageDialog(null, "User ID doesn't exist!", 
                                      "Failed", JOptionPane.ERROR_MESSAGE);
    }

} catch (SQLException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "SQL Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_CondfButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        String confirmedUserId = "someUserId";
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirmation(confirmedUserId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CandfButton;
    private javax.swing.JButton CondfButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField uEmail;
    private javax.swing.JTextField uFName;
    private javax.swing.JTextField uID;
    private javax.swing.JTextField uLName;
    // End of variables declaration//GEN-END:variables
}
