/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibrarianPackage;

import BorrowersPackage.BorrowersDB;
import config.Config;
import config.HashPass;
import config.Session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author SCC
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        currpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        hide1 = new javax.swing.JLabel();
        show1 = new javax.swing.JLabel();
        newpass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        hide2 = new javax.swing.JLabel();
        show2 = new javax.swing.JLabel();
        conpass = new javax.swing.JPasswordField();
        discard = new javax.swing.JButton();
        appchanges = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ChangePassIcon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 60));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel2.setText("Change Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 180, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel3.setText("Update password for enhanced account security.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 280, 20));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Current Password*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 140, 20));

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hideMouseReleased(evt);
            }
        });
        jPanel1.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, 20));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/show.png"))); // NOI18N
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, 20));
        jPanel1.add(currpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 260, 40));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("New Password*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 120, 20));

        hide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide.png"))); // NOI18N
        hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hide1MouseReleased(evt);
            }
        });
        jPanel1.add(hide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 20));

        show1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/show.png"))); // NOI18N
        jPanel1.add(show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 20));

        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });
        jPanel1.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 260, 40));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Confirm New Password*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 180, 20));

        hide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide.png"))); // NOI18N
        hide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hide2MouseReleased(evt);
            }
        });
        jPanel1.add(hide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 20));

        show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/show.png"))); // NOI18N
        jPanel1.add(show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 20));

        conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpassActionPerformed(evt);
            }
        });
        jPanel1.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 260, 40));

        discard.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        discard.setText("Discard");
        discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardActionPerformed(evt);
            }
        });
        jPanel1.add(discard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 170, 40));

        appchanges.setBackground(new java.awt.Color(0, 102, 255));
        appchanges.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        appchanges.setText("Apply Changes");
        appchanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appchangesActionPerformed(evt);
            }
        });
        jPanel1.add(appchanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassActionPerformed

    private void appchangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appchangesActionPerformed
        try {          
    Config conf = new Config();
    Session sess = Session.getInstance();
    
    // Ensure password fields are initialized
    if (currpass == null || newpass == null || conpass == null) {
        JOptionPane.showMessageDialog(null, "Error: Password fields not initialized!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String query = "SELECT u_password FROM user WHERE u_id = '" + sess.getUid() + "'";    
    ResultSet rs = conf.getData(query);

    if (rs.next()) {
        String storedPasswordHash = rs.getString("u_password");  // Password stored in DB
        
        // Get old password from JPasswordField
        String oldInput = new String(currpass.getPassword()); 
        String oldHash = HashPass.hashPassword(oldInput); // Hash user input

        if (storedPasswordHash.equals(oldHash)) {    
            // Get new password and confirm password from JPasswordField
            String newInput = new String(newpass.getPassword()); 
            String confirmInput = new String(conpass.getPassword());

            // Validate new password length
            if (newInput.length() < 8) {
                JOptionPane.showMessageDialog(null, "New password must be at least 8 characters!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validate if new password matches confirm password
            if (!newInput.equals(confirmInput)) {
                JOptionPane.showMessageDialog(null, "New password and confirm password do not match!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Hash new password
            String newpassHash = HashPass.hashPassword(newInput); 
            
            String updateQuery = "UPDATE user SET u_password = '" + newpassHash + "' WHERE u_id = '" + sess.getUid() + "'";  
            conf.updateData(updateQuery);
            
            String actions = "Password Change!";
            try (Connection conn = conf.getConnection();
                 PreparedStatement logStmt = conn.prepareStatement(
                     "INSERT INTO logs (id, actions, date) VALUES (?, ?, ?)")) {

                logStmt.setString(1, sess.getUid());
                logStmt.setString(2, actions);
                logStmt.setTimestamp(3, Timestamp.valueOf(LocalDateTime.now()));
                logStmt.executeUpdate();
            }

            JOptionPane.showMessageDialog(null, "Password updated successfully!");
                LibrarianDB ldb = new LibrarianDB();
                this.dispose();
                ldb.setVisible(true);
        } else {    
            JOptionPane.showMessageDialog(null, "Old Password is Incorrect!");
        }
    } else {
        JOptionPane.showMessageDialog(null, "User not found!");
    }    
} catch (SQLException ex) {
    System.out.println("Error: " + ex.getMessage());
}
    }//GEN-LAST:event_appchangesActionPerformed

    private void hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMousePressed
        show.setVisible(true);
        hide.setVisible(false);
        currpass.setEchoChar((char)0);
    }//GEN-LAST:event_hideMousePressed

    private void hideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseReleased
        show.setVisible(false);
        hide.setVisible(true);
        currpass.setEchoChar('*');
    }//GEN-LAST:event_hideMouseReleased

    private void hide1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MousePressed
        show1.setVisible(true);
        hide1.setVisible(false);
        newpass.setEchoChar((char)0);
    }//GEN-LAST:event_hide1MousePressed

    private void hide1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MouseReleased
        show1.setVisible(false);
        hide1.setVisible(true);
        newpass.setEchoChar('*');
    }//GEN-LAST:event_hide1MouseReleased

    private void hide2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide2MousePressed
        show2.setVisible(true);
        hide2.setVisible(false);
        conpass.setEchoChar((char)0);
    }//GEN-LAST:event_hide2MousePressed

    private void hide2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide2MouseReleased
        show2.setVisible(false);
        hide2.setVisible(true);
        conpass.setEchoChar('*');
    }//GEN-LAST:event_hide2MouseReleased

    private void discardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardActionPerformed
        LibrarianDB lbdb = new LibrarianDB();
        this.dispose();
        lbdb.setVisible(true);
    }//GEN-LAST:event_discardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appchanges;
    private javax.swing.JPasswordField conpass;
    private javax.swing.JPasswordField currpass;
    private javax.swing.JButton discard;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel hide1;
    private javax.swing.JLabel hide2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JLabel show;
    private javax.swing.JLabel show1;
    private javax.swing.JLabel show2;
    // End of variables declaration//GEN-END:variables
}
