package BorrowersPackage;


import AdminsPackage.AccPage;
import AdminsPackage.BookWise;
import LibrarianPackage.LibrarianDB;
import Logins.LoginForm;
import config.Session;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class BorrowerDB extends javax.swing.JFrame {

    /**
     * Creates new form BorrowerDB
     */
    public BorrowerDB() {
        initComponents();
    }
    
    Color hover = new Color(0,85,255);  
    Color defbutton = new Color(210,255,255);
    
    Border empty = BorderFactory.createEmptyBorder();
    
    void resetButtonColor(JButton button){
        button.setBackground(defbutton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        dbButton1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bwButton1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbButton1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        accButton1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        logButton1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        uprofile = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        aid = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        afn = new javax.swing.JLabel();
        afname = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        aln = new javax.swing.JLabel();
        alname = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        aemail = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        cn = new javax.swing.JLabel();
        acn = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        type = new javax.swing.JLabel();
        atype = new javax.swing.JLabel();
        changepass = new javax.swing.JLabel();
        forgotpass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(240, 248, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BookWise-removebg-preview.png"))); // NOI18N
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 170));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel1.setText("BORROWER DASHBOARD");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, 50));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 650));

        jPanel6.setBackground(new java.awt.Color(210, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dbButton1.setBackground(new java.awt.Color(210, 255, 255));
        dbButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbButton1MouseExited(evt);
            }
        });
        dbButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setText("DASHBOARD");
        dbButton1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, 30));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard icon.png"))); // NOI18N
        dbButton1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel6.add(dbButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        bwButton1.setBackground(new java.awt.Color(210, 255, 255));
        bwButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bwButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bwButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bwButton1MouseExited(evt);
            }
        });
        bwButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel16.setText("BORROWERS");
        bwButton1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 100, 30));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/customer icon.png"))); // NOI18N
        bwButton1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel6.add(bwButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 160, 50));

        lbButton1.setBackground(new java.awt.Color(210, 255, 255));
        lbButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbButton1MouseExited(evt);
            }
        });
        lbButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel18.setText("LIBRARIAN");
        lbButton1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, 30));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/admin icon.png"))); // NOI18N
        lbButton1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        jPanel6.add(lbButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 150, 50));

        accButton1.setBackground(new java.awt.Color(210, 255, 255));
        accButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accButton1MouseExited(evt);
            }
        });
        accButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel20.setText("ACCOUNT");
        accButton1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, 30));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account icon(1).png"))); // NOI18N
        accButton1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        jPanel6.add(accButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 140, 50));

        logButton1.setBackground(new java.awt.Color(210, 255, 255));
        logButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logButton1MouseExited(evt);
            }
        });
        logButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel22.setText("LOGOUT");
        logButton1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 70, 30));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout icon.png"))); // NOI18N
        logButton1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        jPanel6.add(logButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 130, 50));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 840, 70));

        jPanel1.setBackground(new java.awt.Color(210, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(210, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uprofile.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        uprofile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uprofile.setText("Profile");
        jPanel2.add(uprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 70));

        jPanel4.setBackground(new java.awt.Color(210, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        id.setText("ID:");
        jPanel4.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        aid.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        aid.setText("uid");
        jPanel4.add(aid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 220, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 300, 50));

        jPanel7.setBackground(new java.awt.Color(210, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        afn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        afn.setText("First name:");
        jPanel7.add(afn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        afname.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        afname.setText("afname");
        jPanel7.add(afname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 230, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 300, 50));

        jPanel8.setBackground(new java.awt.Color(210, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aln.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        aln.setText("Last name:");
        jPanel8.add(aln, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        alname.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        alname.setText("alname");
        jPanel8.add(alname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 230, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 300, 50));

        jPanel9.setBackground(new java.awt.Color(210, 255, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        email.setText("Email:");
        jPanel9.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        aemail.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        aemail.setText("email");
        jPanel9.add(aemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 230, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 320, 50));

        jPanel10.setBackground(new java.awt.Color(210, 255, 255));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        cn.setText("Contact number:");
        jPanel10.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        acn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        acn.setText("number");
        jPanel10.add(acn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 230, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 320, 50));

        jPanel11.setBackground(new java.awt.Color(210, 255, 255));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        type.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        type.setText("Type:");
        jPanel11.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        atype.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        atype.setText("type");
        jPanel11.add(atype, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 230, 30));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 320, 50));

        changepass.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 21)); // NOI18N
        changepass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changepass.setText("Change Password");
        jPanel1.add(changepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 200, 30));

        forgotpass.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 21)); // NOI18N
        forgotpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotpass.setText("Forgot Password?");
        jPanel1.add(forgotpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 200, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 840, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dbButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbButton1MouseClicked
        BookWise bwd = new BookWise();
        this.dispose();
        bwd.setVisible(true);
    }//GEN-LAST:event_dbButton1MouseClicked

    private void dbButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbButton1MouseEntered
        dbButton1.setBackground(hover);
    }//GEN-LAST:event_dbButton1MouseEntered

    private void dbButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbButton1MouseExited
        dbButton1.setBackground(defbutton);
    }//GEN-LAST:event_dbButton1MouseExited

    private void bwButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bwButton1MouseClicked
        BorrowerDB bdb = new BorrowerDB();
        this.dispose();
        bdb.setVisible(true);
    }//GEN-LAST:event_bwButton1MouseClicked

    private void bwButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bwButton1MouseEntered
        bwButton1.setBackground(hover);
    }//GEN-LAST:event_bwButton1MouseEntered

    private void bwButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bwButton1MouseExited
        bwButton1.setBackground(defbutton);
    }//GEN-LAST:event_bwButton1MouseExited

    private void lbButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbButton1MouseClicked
        LibrarianDB ldb = new LibrarianDB();
        this.dispose();
        ldb.setVisible(true);
    }//GEN-LAST:event_lbButton1MouseClicked

    private void lbButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbButton1MouseEntered
        lbButton1.setBackground(hover);
    }//GEN-LAST:event_lbButton1MouseEntered

    private void lbButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbButton1MouseExited
        lbButton1.setBackground(defbutton);
    }//GEN-LAST:event_lbButton1MouseExited

    private void accButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accButton1MouseClicked
        AccPage ap = new AccPage();
        this.dispose();
        ap.setVisible(true);
    }//GEN-LAST:event_accButton1MouseClicked

    private void accButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accButton1MouseEntered
        accButton1.setBackground(hover);
    }//GEN-LAST:event_accButton1MouseEntered

    private void accButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accButton1MouseExited
        accButton1.setBackground(defbutton);
    }//GEN-LAST:event_accButton1MouseExited

    private void logButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButton1MouseClicked
        int choice = JOptionPane.showConfirmDialog(
        null,
        "Do you want to logout?",
        "Logout Confirmation",
        JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {
       
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
    }
    }//GEN-LAST:event_logButton1MouseClicked

    private void logButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButton1MouseEntered
        logButton1.setBackground(hover);
    }//GEN-LAST:event_logButton1MouseEntered

    private void logButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButton1MouseExited
        logButton1.setBackground(defbutton);
    }//GEN-LAST:event_logButton1MouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        aid.setText(""+sess.getUid());
        afname.setText(""+sess.getFname());
        alname.setText(""+sess.getLname());
        aemail.setText(""+sess.getEmail());
        acn.setText(""+sess.getContact());
        atype.setText(""+sess.getType());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowerDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowerDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowerDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowerDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowerDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accButton1;
    private javax.swing.JLabel acn;
    private javax.swing.JLabel aemail;
    private javax.swing.JLabel afn;
    private javax.swing.JLabel afname;
    private javax.swing.JLabel aid;
    private javax.swing.JLabel aln;
    private javax.swing.JLabel alname;
    private javax.swing.JLabel atype;
    private javax.swing.JPanel bwButton1;
    private javax.swing.JLabel changepass;
    private javax.swing.JLabel cn;
    private javax.swing.JPanel dbButton1;
    private javax.swing.JLabel email;
    private javax.swing.JLabel forgotpass;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel lbButton1;
    private javax.swing.JPanel logButton1;
    private javax.swing.JLabel type;
    private javax.swing.JLabel uprofile;
    // End of variables declaration//GEN-END:variables
}
